-- vim.opt.cursorcolumn = true
-- vim.opt.cursorline = true
vim.opt.swapfile = false
vim.opt.relativenumber = true
vim.opt.number = true
vim.cmd([["set guifont='HackGen Console NF'"]])
vim.opt.signcolumn = "yes"
vim.cmd([[set shadafile="NONE"]])
vim.opt.termguicolors = true
